### ISSUE TITLE
"Open BO in Overlay Tool"-Support

### ISSUE THREAD

**Issue by jensbuehl** [CraftySalamander/RTS_Overlay#30]
Idea: Have a route that allows direct forwarding of BOs into your tool.
1 Navigate to your BO in aoe4guides
2 Click on "open in overlay tool"
3 Overlay tool is opened up with the BO ready rightaway

Technically, this would result in a push semantic instead of pull semantic.
The current process with copy/paste is less than ideal. :)

Implementation ideas that pop up in my head:
a) entire BO via query parameter: https://overlaytool.gg?bo=buildorderstringhere
b) BO identifier via query parameter: https://overlaytool.gg?bo=boIdentifier => pull it via the API afterwards
c) maybe something else - I am far from an expert :D

**Comment by debel27** [comment]
I think that's a great idea.

## About providing the entire BO in the URL

This option has the benefit of being stateless. But we have to account for browser limitations regarding the URL size. [This StackOverflow answer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) suggests that 2k characters is the safe limit, though we can probably get away with up to 8k characters.

These numbers may be a bit abstract, so I picked an [AOE4 BO at random](https://aoe4guides.com/builds/TUl77gWBVBqtsY8yNuMe) to get an idea of its size. I serialized it with `encodeUriComponent(JSON.stringify(buildOrder))`, which results in a string containing no irrelevant whitespace. The size of the string is 5424 characters, so it seems we are dangerously close to the acceptable limit.

To mitigate issues, we can "compress" the build order object before passing it to the URL. For instance, `{"food": 10, "wood": 7, "gold": 3, "stone": 28, "builder": 0}` can be rewritten into the compact notation `[10,7,3,28,0]`. But it comes with a few drawbacks of its own, and does not completely remove the risk of URL overflow (namely because of the "notes" parameter).

## About providing the BO identifier in the URL

This option is stateless and does not allow to provide an arbitrary build order to the URL. But it does not have the size limitations of the previous option. 

To implement the feature, the overlay tool will have to know which service to pull the build order data from. There are two options:

  - either that information is stored in the identifier itself, e.g. `https://overlaytool.gg?buildOrderId=aoe4guides|0F98DZ0`
  - either both informations are passed separately in the URL, in which case I would recommend path parameters: `https://overlaytool.gg/aoe4guides/0F98DZ0`

I would be in favor of the second approach.

## Conclusions

Each option comes with a different set of compromises. It might be desirable to support both approaches in the overlay tool.

**Comment by jensbuehl** [comment]
BO identifier in URL would be my preferred solution. You may use the aoe4guides API to retrieve the BO by id in the converted format for your service or use the original document.

A separate source identifier (e.g. separate route as you suggested already) seems reasonable given that you support multiple games and multiples websites.

https://aoe4guides.com/api/api-docs/

Have a nice day :)

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CraftySalamander** [comment]
Hi @jensbuehl 

I started looking at the implementation of this new feature.
However, I receive the following error when I try to fetch the data from `https://aoe4guides.com/api/builds/TUl77gWBVBqtsY8yNuMe?overlay=true`:
-----
Access to fetch at 'https://aoe4guides.com/api/builds/TUl77gWBVBqtsY8yNuMe?overlay=true' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
-----

I am not an expert about it, but it seems it is a safety to prevent a site A to make request on a site B.
To allow another site (like rts-overlay) to fetch the BOs from aoe4guides, you would need to setup an HTTP Access-Control-Allow-Origin response header (see [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)).

Of course, it is up to you to decide if you want to add this feature ;-)

I tested it in the small script in attachment ([test_fetch.txt](https://github.com/user-attachments/files/17722261/test_fetch.txt), to rename to `test_fetch.html`). When I test it with `https://aoe4world.com/api/v0/players/4635035`, everything works as expected.

**Comment by jensbuehl** [comment]
Just to keep track of it when picking it up again:
https://dev.to/speaklouder/how-to-configure-cors-in-nodejs-with-express-11h

The api project is based on node.js and express. It seems to be pretty straight forward to configure CORS properly.

**Comment by jensbuehl** [comment]
What seems strange to me: Why is origin 'null'? Shouldn't this be your server address / domain?
I would not like to free the API up to all - only specific domains if possible...

**Comment by jensbuehl** [comment]
Update: I configured CORS accordingly on server side. Open to all domains, since a public API anyways. Give it a try and fingers crossed :)

**Comment by CraftySalamander** [comment]
Hi @jensbuehl 

Thank you. You updated it very fast.
I tested it and it seems to work. I need to clean a bit my code, to review and then I will send you the instructions to use it :-)

**Comment by CraftySalamander** [comment]
Hi @jensbuehl 

The overlay is ready :-)

You can now open it with this url: `https://rts-overlay.github.io/?gameId=aoe4&buildOrderId=aoe4guides|BO_ID`.

For instance, you can use `https://rts-overlay.github.io/?gameId=aoe4&buildOrderId=aoe4guides|TUl77gWBVBqtsY8yNuMe` to open [this build order](https://aoe4guides.com/builds/TUl77gWBVBqtsY8yNuMe).

The user then only needs to click on 'Display overlay' (after selecting if he wants the overlay on the left or right) to open the overlay.
I also added a button 'Open full page' to open it in a single page, but it is mainly a feature for the other games (in particular AoM), since aoe4guides.com already does it better for AoE4. I took inspiration from aoe4guides and age4builder to color the column with resources (it was a nice idea ;-) ).

**Comment by jensbuehl** [comment]
Seems cool, will take a look when time permits.

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CraftySalamander** [comment]
Hi @jensbuehl 
I tried to look at this feature (I made a fork of your github project).

Under "Overlay Tool (i)" and "Download", I was thinking about adding "Open in RTS Overlay", which would open the page `https://rts-overlay.github.io/?gameId=aoe4&buildOrderId=aoe4guides|BO_ID`.

However, I have some issues running your project.
I followed the instructions on your readme, but got the following error (after running `npm run dev`, in `src/firebase/index.js`, line 48: `const auth = getAuth(app);`):
```
assert.ts:152  Uncaught FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (assert.ts:152:38)
    at _assert (assert.ts:177:11)
    at Component.instanceFactory (register.ts:72:9)
    at Provider.getOrInitializeService (provider.ts:318:33)
    at Provider.initialize (provider.ts:242:27)
    at initializeAuth (initialize.ts:66:25)
    at getAuth (index.ts:83:16)
    at index.js:48:14
```
It seems to be an identification error.
Maybe it is something basic, but my web knowledge is mainly about static websites.

**Comment by CraftySalamander** [comment]
Thanks.
I am not sure myself when I will have time to look into this, and this is not urgent.

**Comment by CraftySalamander** [comment]
@jensbuehl 
I tested it, it works well. Thank you :-)
